# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b066eb591cd7d5e7f9ea68e3b6fdf5d5ee3cba71e47ce90d7bd9eeea3af88d17b3803725bf33f5290b82d9c69f5436fe8ba4aa1289c1c5ef5e272d23ca1603be

test:
  secret_key_base: 5f76ef7b90c5a3d7251c296aca45e3457288a71c2b47a6716240ec7b2bd0b008f92752e449bb60025de16a858018a8a4eca396945f56468fcf7094156df7402e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
